site_name: Waraq
site_url: https://diyar-ali.github.io/
theme:
  name: material
  font:
    text: Poppins
    code: Patrick Hand
  icon:
    logo: fontawesome/solid/pen-nib
  favicon: images/favicon.svg
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
      

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  analytics:
    provider: google
    property: G-DMNLDMXTQE
  social:
    - icon: fontawesome/brands/github
      link: www.github.com/diyar-ali
    - icon: fontawesome/brands/twitter
      link: www.github.com/diyar-ali
    - icon: fontawesome/brands/linkedin
      link: www.github.com/diyar-ali

copyright: "© 2024 Waraqah. All rights reserved."